### ISSUE TITLE
geany-plugins depends on obsolete net-libs/webkit-gtk

### ISSUE THREAD

**Issue by marv** [sardemff7/sardemff7-exheres#12]
Hey @sardemff7 
Are you still using geany and it's plugins? The plugins package depends on `net-libs/webkit-gtk` which we would like to get rid of.
I can make a PR to bury the packages if you're okay with it

**Comment by sardemff7** [comment]
I am using them, but with GTK 3, and I’ll probably drop GTK 2 support with their next release anyway.
Dropped the dep (and plugins requiring it) in 229ce5215e3aeee1bb9482336c4e9444d98a51c4.
